title:              Mザウルスのデータ解析記録
email:              imamura.mei.eu@gmail.com
description:        バイオインフォマティクス解析時の記録の一部を残しています
author:             M-DiSa
baseurl:            "/blog-jekyll-page"
url:                "https://m-disa.github.io"

# Social Profiles
twitter_username:   Dザウルス
github_username:    M-DiSa
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
